import amr0 from "../../assets/images/amr0.png";import amr1 from "../../assets/images/amr1.png";
import amr2 from "../../assets/images/amr2.png";
import amr3 from "../../assets/images/amr3.png";
import amr4 from "../../assets/images/amr4.png";
import amr5 from "../../assets/images/amr5.png";
import amr6 from "../../assets/images/amr6.png";
import amr7 from "../../assets/images/amr7.png";

const menu = [
  {
    id: 1,
    src: amr0,
    alt: "it's a photo",
    title: "imdb clone",
    category: "react",
    description: "the project based on React",
    activeObject: null,
    live: "https://amr-abd-alhameed.github.io/IMDB-CLONE/",
    demo: "https://github.com/amr-abd-alhameed/IMDB-CLONE",
    tech: [
      {
        html: "html",
        css: "css",
        scss: "scss",
        bootstrap: "bootstrap",
        tailwind: "tailwind",
        js: "javascript",
        react: "react",
        redux: "redux",
        reduxToolkit: "redux Toolkit",
        framerMotion: "framer Motion",
        hooks: "hooks",
        reactSkeleton: "react Skeleton",
        carousel: "carousel",
        reactRouter: "react Router",
        marquee: "marquee",
        reactIcons: "react Icons",
        reactImageZoom: "react-Image-Zoom",
        styledComponent: "styled Component",
      },
    ],
  },
  {
    id: 2,
    src: amr1,
    alt: "it's a photo",
    title: "the name of project",
    category: "react",
    description: "the project based on React",
    activeObject: null,
    live: "https://amr-abd-alhameed.github.io/ToDoApp/",
    demo: "https://github.com/amr-abd-alhameed/ToDoApp",
    tech: "",
  },
  {
    id: 3,
    src: amr2,
    alt: "it's a photo",
    title: "the name of project",
    category: "js react",
    description: "the project based on React",
    activeObject: null,
    live: "https://amr-abd-alhameed.github.io/e-commerce-app/",
    demo: "https://github.com/amr-abd-alhameed/e-commerce-app",
    tech: "",
  },
  {
    id: 4,
    src: amr3,
    alt: "it's a photo",
    title: "the name of project",
    category: "js",
    description: "the project based on React",
    activeObject: null,
    live: "https://amr-abd-alhameed.github.io/portfolio1/",
    demo: "https://github.com/amr-abd-alhameed/portfolio1",
    tech: "",
  },
  {
    id: 5,
    src: amr4,
    alt: "it's a photo",
    title: "the name of project",
    category: "js",
    description: "the project based on React",
    activeObject: null,
    live: "https://amr-abd-alhameed.github.io/dashBoard/",
    demo: "https://github.com/amr-abd-alhameed/dashBoard",
    tech: "",
  },
  {
    id: 6,
    src: amr5,
    alt: "it's a photo",
    title: "the name of project",
    category: "react",
    description: "the project based on React",
    activeObject: null,
    live: "",
    demo: "",
    tech: "",
  },
  {
    id: 7,
    src: amr6,
    alt: "it's a photo",
    title: "the name of project",
    category: "js",
    description: "the project based on React",
    activeObject: null,
    live: "https://amr-abd-alhameed.github.io/Leon-Templet/",
    demo: "https://github.com/amr-abd-alhameed/Leon-Templet/settings/pages",
  },
  {
    id: 8,
    src: amr7,
    alt: "it's a photo",
    title: "the name of project",
    category: "js",
    description: "the project based on React",
    activeObject: null,
    live: "https://amr-abd-alhameed.github.io/QuizApp/",
    demo: "https://github.com/amr-abd-alhameed/QuizApp",
    tech: "",
  },
];
export default menu;
